modified alt texts under <Image> to be more descriptive
RubySpeeders/Drum-Roulette pull request #67
Opened 2023-08-02 21:26 UTC by cheesehero112

### Summary of Changes

Modified alt texts under <Image> (for both musicians and instruments) to be more descriptive.

modified files: 
- selections.tsx
- assignments.tsx

### Summary of Implementation Logic

### Issue Link

https://github.com/RubySpeeders/Drum-Roulette/issues/51

Original Issue: Issue 51

Dependent Issues:

Depends on Issues:

### Screen shots / Videos
It's getting a pretty good score! 
![Screenshot 2023-08-02 at 2 55 14 PM](https://github.com/RubySpeeders/Drum-Roulette/assets/102322200/fcb5bdda-73f7-4886-ae9a-18141d01193b)

...but I cannot find which image it is not finding "alt" attribute. As far as I can tell, all images have alt. 
![Screenshot 2023-08-02 at 3 06 30 PM](https://github.com/RubySpeeders/Drum-Roulette/assets/102322200/62ac5b33-1719-4f01-ae26-681a8981be33)

### Acceptance Criteria

I tested using chrome's built in tool "lighthouse" to test the current accessibility, however, I'm not sure if the new alt label is working correctly for users who use a tool such as VoiceOver. 

@charlottekies - if you know how to use VoiceOver or other tools similar, I'm curious if you could test it out to see if it's working as expected

---

### Checklist for PR Owner

- [ ] Standardized PR Title
- [ ] Included relevant videos and screen shots
- [ ] Included Summary of Changes
- [ ] Included Summary of Implementation Logic
- [ ] Acceptance Criteria are fufilled

2023-08-04 19:42 UTC, RubySpeeders requested changes

2023-08-04 19:43 UTC, RubySpeeders commented
I am trying to figure out where the other image missing the `alt` attribute is, as well! It might be on a hidden component, maybe part of a library. Have you made any progress on figuring it out? @cheesehero112

2023-08-16 13:39 UTC, RubySpeeders approved these changes

2023-08-16 13:39 UTC, RubySpeeders commented
Looks good!

2023-08-23 00:37 UTC, charlottekies approved these changes

2023-08-23 14:45 UTC, RubySpeeders commented
@cheesehero112 go ahead and merge this one in! I think it looks great.

2023-08-30 16:54 UTC, merged